version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.1.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.
      - ./docker-runtime/mariadb:/var/lib/mysql
    networks:
      simple:
        ipv4_address: "${NETWORK_PREFIX}.2"



  php:
# 1. Images with vanilla Drupal – wodby/drupal:[DRUPAL_VERSION]-[PHP_VERSION]-[STABILITY_TAG].
#    image: wodby/drupal:8-7.1-2.1.2
#    image: wodby/drupal:8-7.0-2.1.2
#    image: wodby/drupal:7-7.1-2.1.2
#    image: wodby/drupal:7-7.0-2.1.2
#    image: wodby/drupal:7-5.6-2.1.2
#    image: wodby/drupal:6-5.6-2.1.2
#    image: wodby/drupal:6-5.3-2.1.2
# 2. Images without Drupal – wodby/drupal-php:[PHP_VERSION]-[STABILITY_TAG].
#    image: wodby/drupal-php:7.1-2.1.0
#    image: wodby/drupal-php:7.0-2.1.0
    image: wodby/drupal-php:5.6-2.1.0
#    image: wodby/drupal-php:5.3-2.1.0
    environment: # find more env variables here https://github.com/wodby/php
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_DRIVER: mysql
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_MAX_EXECUTION_TIME: 60
      PHP_MEMORY_LIMIT: 1024M
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
#      - codebase:/var/www/html
#     - docker-sync:/var/www/html # Docker-sync for macOS users
      - ./web:/var/www/html
    networks:
      simple:
        ipv4_address: "${NETWORK_PREFIX}.3"



  nginx:
# wodby/drupal-nginx:[DRUPAL_VERSION]-[NGINX_VERSION]-[STABILITY_TAG].
    image: wodby/drupal-nginx:8-1.10-2.1.0
#    image: wodby/drupal-nginx:7-1.10-2.1.0
#    image: wodby/drupal-nginx:6-1.10-2.1.0
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
    volumes:
#      - codebase:/var/www/html
#      - docker-sync:/var/www/html # Docker-sync for macOS users
      - ./web:/var/www/html
    labels:
      - "traefik.backend=nginx"
      - "traefik.port=80"
      # For multiple hosts (Drupal MultiSiting)
      - "traefik.frontend.rule=HostRegexp:${PROJECT_NAME}.web.docker.localhost, {subdomain:[A-Za-z0-9-]+}.${PROJECT_NAME}.web.docker.localhost"
    networks:
      simple:
        ipv4_address: "${NETWORK_PREFIX}.4"



#  varnish:
#    image: wodby/drupal-varnish:4.1-2.1.0
#    depends_on:
#      - nginx
#    environment:
#      VARNISH_SECRET: secret
#      VARNISH_BACKEND_HOST: nginx
#      VARNISH_BACKEND_PORT: 80
#    labels:
#      - "traefik.backend=varnish"
#      - "traefik.port=6081"
#      - "traefik.frontend.rule=Host:${PROJECT_NAME}.varnish.docker.localhost"
#    networks:
#      simple:
#        ipv4_address: "${NETWORK_PREFIX}.5"



#  redis:
#    image: wodby/redis:3.2-2.1.0
#    networks:
#      simple:
#        ipv4_address: "${NETWORK_PREFIX}.6"



#  pma:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      PMA_HOST: mariadb
#      PMA_USER: ${DB_USER}
#      PMA_PASSWORD: ${DB_PASSWORD}
#      PHP_UPLOAD_MAX_FILESIZE: 1G
#      PHP_MAX_INPUT_VARS: 1G
#    labels:
#      - "traefik.backend=pma"
#      - "traefik.port=80"
#      - "traefik.frontend.rule=Host:${PROJECT_NAME}.pma.docker.localhost"
#    networks:
#      simple:
#        ipv4_address: "${NETWORK_PREFIX}.7"



#  solr: # admin configs in SearchApi: http://solr:8000/solr/{core_name}
## wodby/drupal-solr:[DRUPAL_VERSION]-[SOLR_VERSION]-[STABILITY_TAG].
#    image: wodby/drupal-solr:8-6.4-2.0.0
##    image: wodby/drupal-solr:8-6.3-2.0.0
##    image: wodby/drupal-solr:8-5.5-2.0.0
##    image: wodby/drupal-solr:7-6.4-2.0.0
##    image: wodby/drupal-solr:7-6.3-2.0.0
#    image: wodby/drupal-solr:7-5.5-2.0.0
##    image: solr:5.5-alpine
#    environment:
#      SOLR_HEAP: 1024m
#    labels:
#      - "traefik.backend=solr"
#      - "traefik.port=8983"
#      - "traefik.frontend.rule=Host:${PROJECT_NAME}.solr.docker.localhost"
#    volumes:
#      - ./docker-runtime/solr:/opt/solr/server/solr/
#    networks:
#      simple:
#        ipv4_address: "${NETWORK_PREFIX}.8"



  mailhog:
    image: mailhog/mailhog
    labels:
      - "traefik.backend=mailhog"
      - "traefik.port=8025"
      - "traefik.frontend.rule=Host:${PROJECT_NAME}.mailhog.docker.localhost"
    networks:
      simple:
        ipv4_address: "${NETWORK_PREFIX}.9"



#  node:
#    image: node:7-alpine
#    working_dir: /app
#    labels:
#      - "traefik.backend=node"
#      - "traefik.port=3000"
#      - "traefik.frontend.rule=Host:${PROJECT_NAME}.front.docker.localhost"
#    expose:
#      - "3000"
#    volumes:
#      - ./path/to/your/single-page-app:/app
#    command: sh -c 'npm install && npm run start'
#    networks:
#      simple:
#        ipv4_address: "${NETWORK_PREFIX}.10"



#  memcached:
#    image: wodby/memcached:1.4-2.0.0
#    networks:
#      simple:
#        ipv4_address: "${NETWORK_PREFIX}.11"



  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
#      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.backend=traefik"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:${PROJECT_NAME}.traefik.docker.localhost"
    networks:
      simple:
        ipv4_address: "${NETWORK_PREFIX}.12"





volumes:
  codebase:
## Docker-sync for macOS users
#  docker-sync:
#    external: true





networks:
  simple:
    driver: bridge
    ipam:
     config:
       - subnet: "${NETWORK_PREFIX}.0/16"
         gateway: "${NETWORK_PREFIX}.1"
